var htmlData = [
    // --- 1. Main Root & Metadata (أساسيات المستند) ---
    {
        id: "html-doctype",
        name: "!DOCTYPE html",
        arabicName: "نوع المستند",
        category: "1. أساسيات المستند (Structure)",
        description: "ليس وسماً بحد ذاته، بل هو تعليمة تخبر المتصفح بنسخة HTML المستخدمة (HTML5). يجب أن يكون في أول سطر.",
        syntax: '<!DOCTYPE html>',
        usage: "لضمان عرض الصفحة بشكل صحيح كـ HTML5.",
        values: [],
        examples: [],
        notes: ["بدونه قد يدخل المتصفح في وضع Quirks Mode القديم."],
        relatedElements: [{ element: "html", relationship: "العنصر الجذري الذي يليه مباشرة", linkTo: "#html-html" }]
    },
    {
        id: "html-html",
        name: "html",
        arabicName: "جذر الصفحة",
        category: "1. أساسيات المستند (Structure)",
        description: "العنصر الجذري (Root Element) الذي يغلف كل محتوى الصفحة.",
        syntax: '<html lang="ar" dir="rtl">\n  ...\n</html>',
        usage: "الحاوية الرئيسية للمستند.",
        values: [
            { value: "lang", description: "تحديد لغة الصفحة (مهم لـ SEO و Screen Readers).", example: 'lang="ar"' },
            { value: "dir", description: "اتجاه النص (rtl للعربية).", example: 'dir="rtl"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-head",
        name: "head",
        arabicName: "رأس المستند",
        category: "1. أساسيات المستند (Structure)",
        description: "حاوية للبيانات الوصفية (Metadata) التي لا تظهر للمستخدم، مثل العنوان والروابط.",
        syntax: '<head>\n  <title>...</title>\n</head>',
        usage: "تعريف إعدادات الصفحة، ربط الستايلات والسكربتات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: [
            { element: "body", relationship: "جسم الصفحة الذي يحتوي العناصر المرئية", linkTo: "#html-body" }
        ]
    },
    {
        id: "html-body",
        name: "body",
        arabicName: "جسم المستند",
        category: "1. أساسيات المستند (Structure)",
        description: "يحتوي على كل العناصر المرئية للمستخدم في الصفحة (نصوص، صور، روابط...).",
        syntax: '<body>\n  <h1>مرحبا</h1>\n</body>',
        usage: "الحاوية لكل ما يعرض على الشاشة.",
        values: [],
        examples: [],
        notes: ["يوجد عنصر body واحد فقط في الصفحة."],
        relatedElements: []
    },
    {
        id: "html-title",
        name: "title",
        arabicName: "عنوان الصفحة",
        category: "2. البيانات الوصفية (Metadata)",
        description: "يحدد عنوان المستند الذي يظهر في شريط المتصفح (Browser Tab) ونتائج البحث.",
        syntax: '<title>موقعي الشخصي</title>',
        usage: "أهم عنصر لـ SEO وتجربة المستخدم.",
        values: [],
        examples: [],
        notes: ["يجب أن يكون نصاً فقط (لا يحتوي وسوم)."],
        relatedElements: []
    },
    {
        id: "html-meta",
        name: "meta",
        arabicName: "بيانات وصفية",
        category: "2. البيانات الوصفية (Metadata)",
        description: "يستخدم لتعريف الميتاداتا مثل الترميز، الوصف، الكلمات المفتاحية، وإعدادات العرض.",
        syntax: '<meta charset="UTF-8">\n<meta name="description" content="...">',
        usage: "SEO، ضبط العرض للموبايل، ترميز الحروف.",
        values: [
            { value: "charset", description: "ترميز الحروف (غالباً UTF-8).", example: 'charset="UTF-8"' },
            { value: "name", description: "اسم الخاصية (viewport, description).", example: 'name="viewport"' },
            { value: "content", description: "قيمة الخاصية.", example: 'content="width=device-width"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-link",
        name: "link",
        arabicName: "ربط الموارد",
        category: "2. البيانات الوصفية (Metadata)",
        description: "يستخدم لربط المستند بملفات خارجية، أشهر استخدام له هو ربط ملفات CSS.",
        syntax: '<link rel="stylesheet" href="style.css">',
        usage: "استدعاء ملفات الستايل، أيقونة الموقع (Favicon).",
        values: [
            { value: "rel", description: "العلاقة (stylesheet, icon).", example: 'rel="stylesheet"' },
            { value: "href", description: "مسار الملف.", example: 'href="main.css"' }
        ],
        examples: [],
        notes: ["يوضع دائماً داخل <head>.", "عنصر فارغ (لا يغلق)."],
        relatedElements: []
    },
    {
        id: "html-style",
        name: "style",
        arabicName: "تنسيق داخلي",
        category: "2. البيانات الوصفية (Metadata)",
        description: "يستخدم لكتابة أكواد CSS داخل ملف HTML نفسه.",
        syntax: '<style>\n  body { color: red; }\n</style>',
        usage: "التنسيقات الخاصة بصفحة واحدة فقط.",
        values: [],
        examples: [],
        notes: ["يفضل دائماً استخدام ملف خارجي (link) إلا في حالات الضرورة."],
        relatedElements: []
    },
    {
        id: "html-base",
        name: "base",
        arabicName: "المسار الأساسي",
        category: "2. البيانات الوصفية (Metadata)",
        description: "يحدد المسار الأساسي (Base URL) لجميع الروابط النسبية في الصفحة.",
        syntax: '<base href="https://www.example.com/" target="_blank">',
        usage: "توحيد مصدر الروابط والصور.",
        values: [],
        examples: [],
        notes: ["يجب أن يكون أول عنصر في <head> قبل أي رابط آخر."],
        relatedElements: []
    },

    // --- 3. Sectioning (هيكلة المحتوى) ---
    {
        id: "html-header",
        name: "header",
        arabicName: "رأس القسم",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "يمثل مقدمة لصفحة أو قسم، يحتوي عادةً على الشعار والعناوين.",
        syntax: '<header>\n  <h1>الموقع</h1>\n</header>',
        usage: "رأس الموقع، رأس المقال.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-nav",
        name: "nav",
        arabicName: "قائمة تنقل",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "قسم مخصص لروابط التنقل الرئيسية.",
        syntax: '<nav>\n  <a href="#">الرئيسية</a>\n</nav>',
        usage: "القوائم العلوية، الجانبية، الفهرس.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-main",
        name: "main",
        arabicName: "المحتوى الرئيسي",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "الحاوية للمحتوى الفريد والأساسي في الصفحة. لا يتكرر.",
        syntax: '<main>\n  ...\n</main>',
        usage: "يغلف الموضوع الأساسي للصفحة.",
        values: [],
        examples: [],
        notes: ["يستخدم مرة واحدة فقط لكل صفحة."],
        relatedElements: []
    },
    {
        id: "html-section",
        name: "section",
        arabicName: "قسم عام",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "قسم دلالي عام في المستند، عادة يكون له عنوان.",
        syntax: '<section>\n  <h2>خدماتنا</h2>\n</section>',
        usage: "تقسيم الصفحة لأجزاء منطقية (عن الشركة، خدماتنا، اتصل بنا).",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-article",
        name: "article",
        arabicName: "مقال مستقل",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "محتوى مستقل قائم بذاته يمكن إعادة توزيعه (مثل خبر، تدوينة).",
        syntax: '<article>\n  <h2>عنوان الخبر</h2>\n</article>',
        usage: "التدوينات، التعليقات، بطاقات المنتجات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-aside",
        name: "aside",
        arabicName: "محتوى جانبي",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "محتوى مرتبط بشكل ثانوي بالمحتوى الرئيسي (مثل Sidebar).",
        syntax: '<aside>\n  <h3>إعلانات</h3>\n</aside>',
        usage: "أشرطة جانبية، إعلانات، مقالات ذات صلة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-footer",
        name: "footer",
        arabicName: "تذييل",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "تذييل للصفحة أو للقسم، يحتوي حقوق النشر ومعلومات الاتصال.",
        syntax: '<footer> الحقوق محفوظة </footer>',
        usage: "نهاية الصفحة، نهاية المقال.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-headings",
        name: "h1 - h6",
        arabicName: "العناوين",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "عناوين بأحجام وأهمية متفاوتة. h1 الأهم و h6 الأقل.",
        syntax: '<h1>عنوان رئيسي</h1>\n<h2>فرعي</h2>',
        usage: "هرمية محتوى الصفحة.",
        values: [],
        examples: [],
        notes: ["استخدم h1 مرة واحدة للصفحة."],
        relatedElements: []
    },
    {
        id: "html-hgroup",
        name: "hgroup",
        arabicName: "مجموعة عناوين",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "يجمع عنواناً رئيسياً (h1-h6) مع محتوى وصفي مرافق (مثل p).",
        syntax: '<hgroup>\n  <h1>العنوان</h1>\n  <p>شرح</p>\n</hgroup>',
        usage: "عناوين مركبة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-address",
        name: "address",
        arabicName: "عنوان الاتصال",
        category: "3. هيكلة المحتوى (Sectioning)",
        description: "يوفر معلومات الاتصال الخاصة بمالك المستند أو المقال.",
        syntax: '<address>\n  تواصل معنا عبر <a href="mailto:...">البريد</a>\n</address>',
        usage: "في الفوتر أو نهاية المقالات.",
        values: [],
        examples: [],
        notes: ["يعرض عادة بخط مائل."],
        relatedElements: []
    },

    // --- 4. Text Content (المحتوى النصي) ---
    {
        id: "html-p",
        name: "p",
        arabicName: "فقرة",
        category: "4. المحتوى النصي (Text Content)",
        description: "الفقرة النصية (Paragraph).",
        syntax: '<p>هذا نص الفقرة.</p>',
        usage: "الكتل النصية الأساسية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-div",
        name: "div",
        arabicName: "حاوية صندوقية",
        category: "4. المحتوى النصي (Text Content)",
        description: "عنصر حاوية عام (Block-level) يستخدم للتخطيط والتجميع.",
        syntax: '<div class="box">...</div>',
        usage: "CSS Layouts, Grouping.",
        values: [],
        examples: [],
        notes: ["ليس له معنى دلالي."],
        relatedElements: []
    },
    {
        id: "html-hr",
        name: "hr",
        arabicName: "خط فاصل",
        category: "4. المحتوى النصي (Text Content)",
        description: "فاصل موضوعي (Thematic Break) يظهر كخط أفقي.",
        syntax: '<hr>',
        usage: "الفصل بين الفقرات أو المواضيع.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-pre",
        name: "pre",
        arabicName: "نص مسبق التنسيق",
        category: "4. المحتوى النصي (Text Content)",
        description: "يعرض النص تماماً كما كتب (شاملاً المسافات والأسطر).",
        syntax: '<pre>  Text   Here  </pre>',
        usage: "عرض الأكواد، الشعر.",
        values: [],
        examples: [],
        notes: ["يستخدم غالباً مع <code> للأكواد البرمجية."],
        relatedElements: []
    },
    {
        id: "html-blockquote",
        name: "blockquote",
        arabicName: "اقتباس كتلي",
        category: "4. المحتوى النصي (Text Content)",
        description: "يحدد قسماً مقتبساً من مصدر آخر.",
        syntax: '<blockquote cite="source_url">\n  نص مقتبس...\n</blockquote>',
        usage: "الاقتباسات الطويلة.",
        values: [{ value: "cite", description: "رابط المصدر.", example: 'cite="http..."' }],
        examples: [],
        notes: [],
        relatedElements: [{ element: "q", relationship: "اقتباس سطري قصير", linkTo: "#html-q" }]
    },
    {
        id: "html-ol",
        name: "ol",
        arabicName: "قائمة مرتبة",
        category: "4. المحتوى النصي (Text Content)",
        description: "قائمة عناصر مرقمة (Ordered List).",
        syntax: '<ol>\n  <li>أولاً</li>\n</ol>',
        usage: "الخطوات، الترتيب.",
        values: [
            { value: "type", description: "نوع الترقيم (1, a, A, i, I).", example: 'type="A"' },
            { value: "start", description: "رقم البداية.", example: 'start="10"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-menu",
        name: "menu",
        arabicName: "قائمة أوامر",
        category: "4. المحتوى النصي (Text Content)",
        description: "قائمة غير مرتبة مخصصة للأوامر التفاعلية (Toolbar).",
        syntax: '<menu>\n  <li><button>نسخ</button></li>\n</menu>',
        usage: "أشرطة الأدوات.",
        values: [],
        examples: [],
        notes: ["دلالياً مختلفة عن ul."],
        relatedElements: []
    },
    {
        id: "html-ul",
        name: "ul",
        arabicName: "قائمة غير مرتبة",
        category: "4. المحتوى النصي (Text Content)",
        description: "قائمة عناصر نقطية (Unordered List).",
        syntax: '<ul>\n  <li>عنصر</li>\n</ul>',
        usage: "القوائم النقطية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-li",
        name: "li",
        arabicName: "عنصر قائمة",
        category: "4. المحتوى النصي (Text Content)",
        description: "عنصر داخل القائمة (List Item).",
        syntax: '<li>محتوى</li>',
        usage: "داخل ul أو ol.",
        values: [{ value: "value", description: "رقم العنصر (فقط في ol)", example: 'value="5"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-dl",
        name: "dl",
        arabicName: "قائمة وصفية",
        category: "4. المحتوى النصي (Text Content)",
        description: "قائمة تعريفات (Description List).",
        syntax: '<dl>\n  <dt>مصطلح</dt>\n  <dd>شرح...</dd>\n</dl>',
        usage: "القواميس، الأسئلة والأجوبة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-dt",
        name: "dt",
        arabicName: "مصطلح التعريف",
        category: "4. المحتوى النصي (Text Content)",
        description: "اسم المصطلح في القائمة الوصفية.",
        syntax: '<dt>HTML</dt>',
        usage: "داخل dl.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-dd",
        name: "dd",
        arabicName: "شرح التعريف",
        category: "4. المحتوى النصي (Text Content)",
        description: "شرح المصطلح في القائمة الوصفية.",
        syntax: '<dd>لغة ترميز...</dd>',
        usage: "داخل dl بعد dt.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-figure",
        name: "figure",
        arabicName: "شكل توضيحي",
        category: "4. المحتوى النصي (Text Content)",
        description: "محتوى مستقل (صورة، رسم بياني، كود) مع شرح اختياري.",
        syntax: '<figure>\n  <img src="...">\n  <figcaption>شرح</figcaption>\n</figure>',
        usage: "الصور مع التسمية التوضيحية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-figcaption",
        name: "figcaption",
        arabicName: "تسمية الشكل",
        category: "4. المحتوى النصي (Text Content)",
        description: "عنوان أو شرح لعنصر figure.",
        syntax: '<figcaption>الرسم البياني 1</figcaption>',
        usage: "داخل figure.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 5. Inline Text Semantics (نصوص دقيقة) ---
    {
        id: "html-a",
        name: "a",
        arabicName: "رابط تشعبي",
        category: "5. النصوص الدلالية (Inline)",
        description: "Anchor - ينشئ رابطاً لصفحة أخرى، ملف، مكان، أو بريد.",
        syntax: '<a href="url">الرابط</a>',
        usage: "التنقل.",
        values: [
            { value: "href", description: "الوجهة.", example: 'href="page.html"' },
            { value: "target", description: "مكان الفتح (_blank نافذة جديدة).", example: 'target="_blank"' },
            { value: "download", description: "تنزيل الملف بدلاً من فتحه.", example: "download" }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-span",
        name: "span",
        arabicName: "حاوية سطرية",
        category: "5. النصوص الدلالية (Inline)",
        description: "حاوية عامة (Inline) لتنسيق جزء من النص.",
        syntax: '<span>نص ملون</span>',
        usage: "تنسيق كلمات محددة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-strong",
        name: "strong",
        arabicName: "نص هام",
        category: "5. النصوص الدلالية (Inline)",
        description: "يدل على أهمية قوية للنص (يعرض عريضاً Bold عادة).",
        syntax: '<strong>تحذير</strong>',
        usage: "الكلمات المفتاحية الهامة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-em",
        name: "em",
        arabicName: "توكيد لفظي",
        category: "5. النصوص الدلالية (Inline)",
        description: "Emphasis - توكيد على الكلام (يعرض مائلاً Italic عادة).",
        syntax: '<em>حقاً</em>',
        usage: "تغيير نبرة القراءة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-b",
        name: "b",
        arabicName: "خط عريض",
        category: "5. النصوص الدلالية (Inline)",
        description: "يجعل النص عريضاً لأغراض بصرية (Keywords) دون أهمية دلالية قوية.",
        syntax: '<b>انتباه</b>',
        usage: "لفت النظر.",
        values: [],
        examples: [],
        notes: ["استخدم strong للأهمية و b للشكل فقط."],
        relatedElements: []
    },
    {
        id: "html-i",
        name: "i",
        arabicName: "خط مائل",
        category: "5. النصوص الدلالية (Inline)",
        description: "نص بصوت أو مزاج بديل (مصطلحات تقنية، كلمات أجنبية).",
        syntax: '<i>Taxonomy</i>',
        usage: "المصطلحات، أسماء السفن.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-u",
        name: "u",
        arabicName: "خط تحت النص",
        category: "5. النصوص الدلالية (Inline)",
        description: "Unarticulated - نص ذو تهميش غير منطوق (مثل الأخطاء الإملائية).",
        syntax: '<u>خطأ</u>',
        usage: "الإشارة للأخطاء.",
        values: [],
        examples: [],
        notes: ["تجنب استخدامه للروابط."],
        relatedElements: []
    },
    {
        id: "html-mark",
        name: "mark",
        arabicName: "تمييز (هايلات)",
        category: "5. النصوص الدلالية (Inline)",
        description: "تمييز النص بلون خلفية (للإشارة للمطابقة أو الأهمية الحالية).",
        syntax: '<mark>بحث</mark>',
        usage: "نتائج البحث.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-s",
        name: "s",
        arabicName: "مشطوب",
        category: "5. النصوص الدلالية (Inline)",
        description: "نص لم يعد دقيقاً أو ذا صلة (Strikethrough).",
        syntax: '<s>50$</s> 20$',
        usage: "الأسعار القديمة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-br",
        name: "br",
        arabicName: "كسر السطر",
        category: "5. النصوص الدلالية (Inline)",
        description: "ينزل سطراً جديداً (Line Break).",
        syntax: 'سطر<br>جديد',
        usage: "الشعر، العناوين البريدية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-wbr",
        name: "wbr",
        arabicName: "فرصة كسر السطر",
        category: "5. النصوص الدلالية (Inline)",
        description: "Word Break Opportunity - يخبر المتصفح أين يمكن كسر الكلمة الطويلة إذا لزم الأمر.",
        syntax: 'Word<wbr>Break',
        usage: "الكلمات الطويلة جداً.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-cite",
        name: "cite",
        arabicName: "مرجع",
        category: "5. النصوص الدلالية (Inline)",
        description: "عنوان عمل فني (كتاب، فيلم، ورقة بحثية).",
        syntax: '<cite>Harry Potter</cite>',
        usage: "المراجع والمصادر.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-q",
        name: "q",
        arabicName: "اقتباس قصير",
        category: "5. النصوص الدلالية (Inline)",
        description: "اقتباس سطري قصير (يضيف المتصفح علامات التنصيص تلقائياً).",
        syntax: '<q>قال ...</q>',
        usage: "الاقتباسات ضمن النص.",
        values: [{ value: "cite", description: "رابط المصدر.", example: 'cite="..."' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-abbr",
        name: "abbr",
        arabicName: "اختصار",
        category: "5. النصوص الدلالية (Inline)",
        description: "اختصار كلمة (Abbreviation).",
        syntax: '<abbr title="HyperText Markup Language">HTML</abbr>',
        usage: "توضيح الاختصارات.",
        values: [{ value: "title", description: "الاسم الكامل.", example: 'title="..."' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-code",
        name: "code",
        arabicName: "كود برمجي",
        category: "5. النصوص الدلالية (Inline)",
        description: "نص يمثل كود حاسوب (خط Monospace).",
        syntax: '<code>console.log()</code>',
        usage: "عرض الأكواد.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-time",
        name: "time",
        arabicName: "وقت وتاريخ",
        category: "5. النصوص الدلالية (Inline)",
        description: "تمثيل وقت أو تاريخ ليكون مقروءاً للآلة.",
        syntax: '<time datetime="2024-01-01">New Year</time>',
        usage: "التواريخ، المواعيد.",
        values: [{ value: "datetime", description: "الصيغة القياسية للوقت.", example: '2024-05-20' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-sub",
        name: "sub",
        arabicName: "نص منخفض",
        category: "5. النصوص الدلالية (Inline)",
        description: "Subscript - نص مصغر منخفض عن السطر.",
        syntax: 'H<sub>2</sub>O',
        usage: "الكيمياء، الرياضيات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-sup",
        name: "sup",
        arabicName: "نص مرتفع",
        category: "5. النصوص الدلالية (Inline)",
        description: "Superscript - نص مصغر مرتفع عن السطر.",
        syntax: 'x<sup>2</sup>',
        usage: "الأسس، الهوامش.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-small",
        name: "small",
        arabicName: "نص صغير",
        category: "5. النصوص الدلالية (Inline)",
        description: "الطباعة الصغيرة (Small Print) مثل حقوق النشر والشروط.",
        syntax: '<small>&copy; 2026</small>',
        usage: "الهوامش القانونية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-ruby",
        name: "ruby",
        arabicName: "روبي",
        category: "5. النصوص الدلالية (Inline)",
        description: "حاوية لنصوص الشرح (تستخدم للغات شرق آسيا).",
        syntax: '<ruby>漢 <rt>kan</rt></ruby>',
        usage: "شرح نطق الحروف.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-rt",
        name: "rt",
        arabicName: "نص روبي",
        category: "5. النصوص الدلالية (Inline)",
        description: "النص الشارح داخل ruby.",
        syntax: '<rt>kan</rt>',
        usage: "داخل ruby.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-rp",
        name: "rp",
        arabicName: "أقواس روبي",
        category: "5. النصوص الدلالية (Inline)",
        description: "أقواس احتياطية للمتصفحات التي لا تدعم ruby.",
        syntax: '<rp>(</rp><rt>...</rt><rp>)</rp>',
        usage: "التوافقية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-kbd",
        name: "kbd",
        arabicName: "إدخال لوحة مفاتيح",
        category: "5. النصوص الدلالية (Inline)",
        description: "يمثل إدخال المستخدم (Keyboard Input).",
        syntax: '<kbd>Ctrl</kbd> + <kbd>C</kbd>',
        usage: "شرح اختصارات الكيبورد.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-samp",
        name: "samp",
        arabicName: "عينة مخرجات",
        category: "5. النصوص الدلالية (Inline)",
        description: "Sample - يمثل عينة من مخرجات برنامج حاسوبي.",
        syntax: '<samp>Error 404</samp>',
        usage: "رسائل النظام.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-bdo",
        name: "bdo",
        arabicName: "تجاوز الاتجاه",
        category: "5. النصوص الدلالية (Inline)",
        description: "Bi-Directional Override - يعكس اتجاه النص إجبارياً.",
        syntax: '<bdo dir="rtl">Text</bdo>',
        usage: "فرض اتجاه معين.",
        values: [{ value: "dir", description: "rtl أو ltr (مطلوب).", example: 'dir="rtl"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-bdi",
        name: "bdi",
        arabicName: "عزل الاتجاه",
        category: "5. النصوص الدلالية (Inline)",
        description: "Bi-Directional Isolation - يعزل جزءاً من النص عن اتجاه النص المحيط به.",
        syntax: '<bdi>User1</bdi>: Hello',
        usage: "عند عرض نصوص مجهولة الاتجاه (مثل تعليقات المستخدمين).",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-data",
        name: "data",
        arabicName: "بيانات مرتبطة",
        category: "5. النصوص الدلالية (Inline)",
        description: "يربط محتوى نصي بقيمة مقروءة للآلة.",
        syntax: '<data value="123">Product 1</data>',
        usage: "ربط المنتجات بمعرفاتها.",
        values: [{ value: "value", description: "القيمة الآلية.", example: 'value="10"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-var",
        name: "var",
        arabicName: "متغير",
        category: "5. النصوص الدلالية (Inline)",
        description: "يمثل متغيراً في تعبير رياضي أو برمجي.",
        syntax: '<var>x</var> = <var>y</var> + 2',
        usage: "المعادلات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 6. Media (الوسائط) ---
    {
        id: "html-img",
        name: "img",
        arabicName: "صورة",
        category: "6. الوسائط (Media)",
        description: "تضمين صورة.",
        syntax: '<img src="img.jpg" alt="وصف">',
        usage: "عرض الصور.",
        values: [
            { value: "src", description: "مسار الصورة.", example: 'src="pic.png"' },
            { value: "alt", description: "النص البديل (مهم).", example: 'alt="Logo"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-audio",
        name: "audio",
        arabicName: "صوت",
        category: "6. الوسائط (Media)",
        description: "مشغل صوتي.",
        syntax: '<audio src="sound.mp3" controls></audio>',
        usage: "تشغيل ملفات الصوت.",
        values: [
            { value: "controls", description: "إظهار التحكم.", example: "controls" },
            { value: "autoplay", description: "تشغيل تلقائي.", example: "autoplay" }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-video",
        name: "video",
        arabicName: "فيديو",
        category: "6. الوسائط (Media)",
        description: "مشغل فيديو.",
        syntax: '<video src="movie.mp4" controls></video>',
        usage: "تشغيل الفيديوهات.",
        values: [
            { value: "poster", description: "صورة الغلاف.", example: 'poster="cover.jpg"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-picture",
        name: "picture",
        arabicName: "صورة متقدمة",
        category: "6. الوسائط (Media)",
        description: "حاوية تتيح توفير مصادر صور متعددة لظروف عرض مختلفة (Art Direction).",
        syntax: '<picture>\n  <source ...>\n  <img ...>\n</picture>',
        usage: "صور متجاوبة، صيغ حديثة (WebP).",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-source",
        name: "source",
        arabicName: "مصدر وسائط",
        category: "6. الوسائط (Media)",
        description: "يحدد مصادر وسائط متعددة لعناصر picture, audio, video.",
        syntax: '<source src="video.webm" type="video/webm">',
        usage: "توفير صيغ بديلة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-track",
        name: "track",
        arabicName: "مسار نصي",
        category: "6. الوسائط (Media)",
        description: "نصوص مصاحبة للوسائط (ترجمة، شرح) للفيديو والصوت.",
        syntax: '<track kind="subtitles" src="subs.vtt" srclang="ar">',
        usage: "الترجمة (Subtitles).",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-map",
        name: "map",
        arabicName: "خريطة صور",
        category: "6. الوسائط (Media)",
        description: "تستخدم لتعريف خريطة صورة تفاعلية (مناطق قابلة للنقر داخل الصورة).",
        syntax: '<map name="workmap">\n  <area ...>\n</map>',
        usage: "صور تحتوي روابط متعددة في أجزاء مختلفة.",
        values: [{ value: "name", description: "اسم الخريطة لربطها بالصورة.", example: 'name="map1"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-area",
        name: "area",
        arabicName: "منطقة خريطة",
        category: "6. الوسائط (Media)",
        description: "تحدد منطقة داخل خريطة الصورة.",
        syntax: '<area shape="rect" coords="34,44,270,350" href="...">',
        usage: "داخل map.",
        values: [{ value: "shape", description: "الشكل (rect, circle, poly).", example: "rect" }],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 7. Embedded Content (تضمين) ---
    {
        id: "html-iframe",
        name: "iframe",
        arabicName: "إطار مضمن",
        category: "7. المحتوى المضمن (Embedded)",
        description: "تضمين صفحة ويب أخرى داخل الصفحة الحالية.",
        syntax: '<iframe src="https://example.com"></iframe>',
        usage: "يوتيوب، خرائط جوجل.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-embed",
        name: "embed",
        arabicName: "تضمين",
        category: "7. المحتوى المضمن (Embedded)",
        description: "نقطة تضمين لمحتوى خارجي غير HTML (تاريخياً للفلاش).",
        syntax: '<embed src="file.swf">',
        usage: "نادر الاستخدام حالياً.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-object",
        name: "object",
        arabicName: "كائن خارجي",
        category: "7. المحتوى المضمن (Embedded)",
        description: "تضمين موارد خارجية (صور، PDF، صفحات).",
        syntax: '<object data="file.pdf"></object>',
        usage: "عرض ملفات PDF.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-param",
        name: "param",
        arabicName: "معامل",
        category: "7. المحتوى المضمن (Embedded)",
        description: "تمرير معاملات للplugins داخل object.",
        syntax: '<param name="autoplay" value="true">',
        usage: "داخل object.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-svg",
        name: "svg",
        arabicName: "رسوميات متجهة",
        category: "7. المحتوى المضمن (Embedded)",
        description: "Scalable Vector Graphics - لإنشاء رسوميات متجهة داخل HTML.",
        syntax: '<svg width="100" height="100">...</svg>',
        usage: "الأيقونات، الرسوم البيانية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-canvas",
        name: "canvas",
        arabicName: "لوحة رسم",
        category: "7. المحتوى المضمن (Embedded)",
        description: "مساحة للرسم البرمجي (بواسطة JS).",
        syntax: '<canvas id="myCanvas"></canvas>',
        usage: "الألعاب، الرسوم البيانية الديناميكية.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 8. Scripting (البرمجة) ---
    {
        id: "html-script",
        name: "script",
        arabicName: "سكربت",
        category: "8. البرمجة (Scripting)",
        description: "كود JavaScript أو رابط لملف JS.",
        syntax: '<script src="app.js"></script>',
        usage: "التفاعلية والمنطق.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-noscript",
        name: "noscript",
        arabicName: "بديل السكربت",
        category: "8. البرمجة (Scripting)",
        description: "محتوى يظهر فقط إذا كان JavaScript معطلاً في المتصفح.",
        syntax: '<noscript>فعل الجافاسكربت!</noscript>',
        usage: "رسائل التنبيه.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 9. Tables (الجداول) ---
    {
        id: "html-table",
        name: "table",
        arabicName: "جدول",
        category: "9. الجداول (Tables)",
        description: "إنشاء جدول بيانات.",
        syntax: '<table>...</table>',
        usage: "عرض البيانات المجدولة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-caption",
        name: "caption",
        arabicName: "عنوان الجدول",
        category: "9. الجداول (Tables)",
        description: "عنوان يظهر فوق الجدول.",
        syntax: '<caption>مبيعات 2024</caption>',
        usage: "داخل table (أول عنصر).",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-thead",
        name: "thead",
        arabicName: "رأس الجدول",
        category: "9. الجداول (Tables)",
        description: "تجميع صفوف الرأس.",
        syntax: '<thead>...</thead>',
        usage: "تنظيم هيكلي.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-tbody",
        name: "tbody",
        arabicName: "جسم الجدول",
        category: "9. الجداول (Tables)",
        description: "تجميع صفوف البيانات.",
        syntax: '<tbody>...</tbody>',
        usage: "الحاوية الرئيسية للصفوف.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-tfoot",
        name: "tfoot",
        arabicName: "تذييل الجدول",
        category: "9. الجداول (Tables)",
        description: "تجميع صفوف التذييل (مجاميع).",
        syntax: '<tfoot>...</tfoot>',
        usage: "أسفل الجدول.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-tr",
        name: "tr",
        arabicName: "صف جدول",
        category: "9. الجداول (Tables)",
        description: "Table Row.",
        syntax: '<tr>...</tr>',
        usage: "إنشاء صف.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-th",
        name: "th",
        arabicName: "خلية عنوان",
        category: "9. الجداول (Tables)",
        description: "Table Head Cell - خلية عنوان (عريضة ووسط).",
        syntax: '<th>الاسم</th>',
        usage: "في الصف الأول أو العمود الأول.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-td",
        name: "td",
        arabicName: "خلية بيانات",
        category: "9. الجداول (Tables)",
        description: "Table Data Cell - خلية بيانات عادية.",
        syntax: '<td>أحمد</td>',
        usage: "عرض المعلومات.",
        values: [
            { value: "colspan", description: "دمج أعمدة.", example: 'colspan="2"' },
            { value: "rowspan", description: "دمج صفوف.", example: 'rowspan="2"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-colgroup",
        name: "colgroup",
        arabicName: "مجموعة أعمدة",
        category: "9. الجداول (Tables)",
        description: "تحديد تنسيقات لمجموعة أعمدة كاملة.",
        syntax: '<colgroup><col span="2" class="red"></colgroup>',
        usage: "تنسيق الجدول.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-col",
        name: "col",
        arabicName: "عمود",
        category: "9. الجداول (Tables)",
        description: "تحديد خصائص لعمود واحد أو أكثر.",
        syntax: '<col span="1">',
        usage: "داخل colgroup.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 10. Forms (النماذج) ---
    {
        id: "html-form",
        name: "form",
        arabicName: "نموذج",
        category: "10. النماذج (Forms)",
        description: "منطقة تحتوي عناصر تفاعلية لجمع البيانات.",
        syntax: '<form action="/log" method="POST">...</form>',
        usage: "تسجيل الدخول، البحث.",
        values: [
            { value: "action", description: "وجهة البيانات.", example: 'action="api/login"' },
            { value: "method", description: "طريقة الإرسال (GET/POST).", example: 'method="POST"' }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-input",
        name: "input",
        arabicName: "حقل إدخال",
        category: "10. النماذج (Forms)",
        description: "أهم عنصر إدخال، يختلف شكله حسب النوع.",
        syntax: '<input type="text">',
        usage: "جمع نصوص، أرقام، ملفات.",
        values: [
            { value: "type", description: "text, password, email, number, date, checkbox, radio, file, submit...", example: 'type="email"' },
            { value: "placeholder", description: "نص توضيحي.", example: 'placeholder="الاسم"' }
        ],
        examples: [],
        notes: ["عنصر فارغ."],
        relatedElements: []
    },
    {
        id: "html-label",
        name: "label",
        arabicName: "تسمية",
        category: "10. النماذج (Forms)",
        description: "عنوان نصي لحقل الإدخال.",
        syntax: '<label for="id">الاسم</label>',
        usage: "تحسين الوصولية.",
        values: [{ value: "for", description: "ID الحقل المرتبط.", example: 'for="user"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-textarea",
        name: "textarea",
        arabicName: "مساحة نصية",
        category: "10. النماذج (Forms)",
        description: "حقل إدخال نصي متعدد الأسطر.",
        syntax: '<textarea rows="4"></textarea>',
        usage: "التعليقات، الرسائل الطويلة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-button",
        name: "button",
        arabicName: "زر",
        category: "10. النماذج (Forms)",
        description: "زر قابل للنقر.",
        syntax: '<button type="submit">إرسال</button>',
        usage: "إرسال النماذج، إجراءات JS.",
        values: [
            { value: "type", description: "submit (إرسال), reset (تفريغ), button (عادي).", example: "button" }
        ],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-select",
        name: "select",
        arabicName: "قائمة منسدلة",
        category: "10. النماذج (Forms)",
        description: "قائمة خيارات يختار المستخدم منها.",
        syntax: '<select><option>1</option></select>',
        usage: "اختيار الدولة، الجنس.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-option",
        name: "option",
        arabicName: "خيار",
        category: "10. النماذج (Forms)",
        description: "خيار واحد داخل القائمة.",
        syntax: '<option value="eg">مصر</option>',
        usage: "داخل select أو datalist.",
        values: [{ value: "value", description: "القيمة المرسلة.", example: 'value="1"' }],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-optgroup",
        name: "optgroup",
        arabicName: "مجموعة خيارات",
        category: "10. النماذج (Forms)",
        description: "تجميع الخيارات في عناوين.",
        syntax: '<optgroup label="Europe">...</optgroup>',
        usage: "داخل select.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-datalist",
        name: "datalist",
        arabicName: "قائمة مقترحات",
        category: "10. النماذج (Forms)",
        description: "يوفر إكمال تلقائي (Autocomplete) لحقل input.",
        syntax: '<input list="browsers">\n<datalist id="browsers">...</datalist>',
        usage: "البحث مع اقتراحات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-fieldset",
        name: "fieldset",
        arabicName: "مجموعة حقول",
        category: "10. النماذج (Forms)",
        description: "تجميع عناصر النموذج ذات الصلة وإحاطتها بإطار.",
        syntax: '<fieldset>\n  <legend>بيانات شخصية</legend>\n  ...\n</fieldset>',
        usage: "تنظيم النماذج الكبيرة.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-legend",
        name: "legend",
        arabicName: "عنوان المجموعة",
        category: "10. النماذج (Forms)",
        description: "عنوان لـ fieldset.",
        syntax: '<legend>Title</legend>',
        usage: "داخل fieldset.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-progress",
        name: "progress",
        arabicName: "شريط تقدم",
        category: "10. النماذج (Forms)",
        description: "يمثل نسبة اكتمال مهمة.",
        syntax: '<progress value="70" max="100"></progress>',
        usage: "التحميلات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-meter",
        name: "meter",
        arabicName: "قياس",
        category: "10. النماذج (Forms)",
        description: "قياس قيمة ضمن نطاق معروف (مثل مساحة القرص).",
        syntax: '<meter value="0.6">60%</meter>',
        usage: "إحصائيات.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-output",
        name: "output",
        arabicName: "مخرجات",
        category: "10. النماذج (Forms)",
        description: "نتيجة عملية حسابية.",
        syntax: '<output name="result">0</output>',
        usage: "حاسبة الأسعار.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },

    // --- 11. Interactive & Web Components (تفاعلية) ---
    {
        id: "html-details",
        name: "details",
        arabicName: "تفاصيل",
        category: "11. عناصر تفاعلية (Interactive)",
        description: "عنصر قابل للطي/الفتح لكشف معلومات.",
        syntax: '<details>\n  <summary>المزيد</summary>\n  <p>...</p>\n</details>',
        usage: "Accordion, FAQ.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-summary",
        name: "summary",
        arabicName: "ملخص التفاصيل",
        category: "11. عناصر تفاعلية (Interactive)",
        description: "العنوان الظاهر لعنصر details.",
        syntax: '<summary>اضغط هنا</summary>',
        usage: "داخل details.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-dialog",
        name: "dialog",
        arabicName: "نافذة حوار",
        category: "11. عناصر تفاعلية (Interactive)",
        description: "نافذة منبثقة (Modal/Dialog).",
        syntax: '<dialog>مرحبا</dialog>',
        usage: "التنبيهات.",
        values: [{ value: "open", description: "جعلها ظاهرة.", example: "open" }],
        examples: [],
        notes: ["يتحكم بها عبر JS (showModal)."],
        relatedElements: []
    },
    {
        id: "html-template",
        name: "template",
        arabicName: "قالب",
        category: "11. عناصر تفاعلية (Interactive)",
        description: "محتوى لا يعرض عند التحميل، يستخدم كقالب لتوليد العناصر بواسطة JS.",
        syntax: '<template><div>...</div></template>',
        usage: "توليد العناصر ديناميكياً.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    },
    {
        id: "html-slot",
        name: "slot",
        arabicName: "منفذ",
        category: "11. عناصر تفاعلية (Interactive)",
        description: "عنصر نائب (Placeholder) داخل Shadow DOM.",
        syntax: '<slot name="header"></slot>',
        usage: "Web Components.",
        values: [],
        examples: [],
        notes: [],
        relatedElements: []
    }
];
